version: '3'

services:
  mysql:
    image: mysql:5.7.27
    restart: always
    environment:
      MYSQL_USER: sharetribe
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: sharetribe_development
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ./tmp/mysql:/var/lib/mysql
  web:
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: >
      bash -c "bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/opt/app
      - /opt/app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - mysql
    environment:
      RAILS_ENV: development
      DATABASE_URL: mysql2://sharetribe:secret@mysql/sharetribe_development
  rails-client-assets:
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: >
      bash -c "cd client && npm run build:dev:client"
    volumes:
      - .:/opt/app
      - /opt/app/client/node_modules
    depends_on:
      - mysql
    environment:
      RAILS_ENV: development
      DATABASE_URL: mysql2://sharetribe:secret@mysql/sharetribe_development
  worker:
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: >
      bash -c "bundle exec rake jobs:work"
    volumes:
      - .:/opt/app
      - /opt/app/node_modules
    depends_on:
      - mysql
    environment:
      RAILS_ENV: development
      DATABASE_URL: mysql2://sharetribe:secret@mysql/sharetribe_development
